version: "3.8"
services:
  laravel_app:
    build: ./docker/php
    volumes:
      - ./laravel_src:/workspace

  react_app:
    build: ./docker/node
    volumes:
      - ./todo:/workspace
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"

  web:
    image: nginx:1.20-alpine
    volumes:
      - ./laravel_src:/workspace
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir:
      /workspace
    ports:
      - 8000:80
    depends_on:
      - laravel_app

  db:
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306
    tty: true

volumes:
  db-store:
